[versions]
acraVersion = "5.11.2"
agp = "8.6.0"
androidGifDrawable = "1.2.22"
androidImageCropper = "4.6.0"
faceDetection = "16.1.7"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
ksoap2Android = "3.6.2"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
acra = "4.11.1"
androidMail = "1.6.7"
photoview = "2.0.0"
picasso = "2.8"
playServicesMaps = "19.0.0"
playServicesMapsVersion = "17.0.0"
secretsGradlePlugin = "2.0.1"

[libraries]
acra-core = { module = "ch.acra:acra-core", version.ref = "acraVersion" }
acra-mail = { module = "ch.acra:acra-mail", version.ref = "acraVersion" }
acra-notification = { module = "ch.acra:acra-notification", version.ref = "acraVersion" }
acra-toast = { module = "ch.acra:acra-toast", version.ref = "acraVersion" }
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
ksoap2-android = { module = "com.google.code.ksoap2-android:ksoap2-android", version.ref = "ksoap2Android" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version = "1.9.2" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
acra = { group = "ch.acra", name = "acra", version = "4.11.1" }
android-mail = { group = "com.sun.mail", name = "android-mail", version.ref = "androidMail" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-maps-v1700 = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMapsVersion" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

