[versions]
acraVersion = "5.11.2"
agp = "8.6.0"
androidGifDrawable = "1.2.22"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
ksoap2Android = "3.6.2"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
acra = "4.11.1"
androidMail = "1.6.7"

[libraries]
acra-core = { module = "ch.acra:acra-core", version.ref = "acraVersion" }
acra-mail = { module = "ch.acra:acra-mail", version.ref = "acraVersion" }
acra-notification = { module = "ch.acra:acra-notification", version.ref = "acraVersion" }
acra-toast = { module = "ch.acra:acra-toast", version.ref = "acraVersion" }
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
ksoap2-android = { module = "com.google.code.ksoap2-android:ksoap2-android", version.ref = "ksoap2Android" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version = "1.9.2" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
acra = { group = "ch.acra", name = "acra", version = "4.11.1" }
android-mail = { group = "com.sun.mail", name = "android-mail", version.ref = "androidMail" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

